name: Java CI

on:
  push:
    paths:
      - 'java/**'
      - '.github/workflows/java**'
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/java**'

  schedule:
    # weekly build every FRI
    - cron: "0 6 * * 5"

jobs:

  mvn_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build junit5 with Maven
        working-directory: java/junit5
        run: java --version && mvn --batch-mode --update-snapshots verify
